# 
# Must be sourced
#
SUBSCRIPTION="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
LOCATION=${LOCATION:-australiasoutheast}
NON_COMPLIANT_LOCATION=${NON_COMPLIANT_LOCATION:-westus}
RESOURCE_GROUP_NAME=cld-cmp-poc
VNET_NAME=${RESOURCE_GROUP_NAME}-vnt
VNET_ADDRESS_PREFIX=10.1.0.0/16
VNET_ADDRESS_PREFIX_SUBN1=10.1.1.0/24
VNET_ADDRESS_PREFIX_SUBN2=10.1.2.0/24
VNET_SUBNET_NAME_SUBN1=${RESOURCE_GROUP_NAME}-subn1
VNET_SUBNET_NAME_SUBN2=${RESOURCE_GROUP_NAME}-subn2
VNET_NETWORK_SECURITY_GROUP=${RESOURCE_GROUP_NAME}-nsg
VNET_NIC_NAME_NIC1=${RESOURCE_GROUP_NAME}-nic1
VNET_NIC_NAME_NIC2=${RESOURCE_GROUP_NAME}-nic2
STORAGE_ACCOUNT_NAME=$(echo ${RESOURCE_GROUP_NAME}-strg | tr -d "-")
CONTAINER_NAME=cld-cmp-poc-test-container
VM_NIX_NAME=${RESOURCE_GROUP_NAME}-nix-vm
VM_NIX_SIZE=Standard_B1s
LINUX_COMPLIANT_IMAGE=CentOS
LINUX_NON_COMPLIANT_IMAGE=CoreOS
LINUX_IMAGE_POLICY_ASSIGNMENT=XXXImagePolicy
VM_WIN_NAME=$(echo ${RESOURCE_GROUP_NAME}-win-vm | tr -d "-")
VM_WIN_SIZE=Standard_B2s
WINDOWS_COMPLIANT_IMAGE=Win2016Datacenter
WINDOWS_NON_COMPLIANT_IMAGE=Win2016Datacenter
#
WIN_ADMIN_USER=pocadmin
WIN_ADMIN_PASSWORD=pocPassw0rd123
#
SQLSERVER_NAME=$(echo ${RESOURCE_GROUP_NAME}-sqldb | tr -d "-")
SQLSERVER_START_IP=0.0.0.0
SQLSERVER_END_IP=0.0.0.0
SQLSERVER_FW_RULE_NAME=${RESOURCE_GROUP_NAME}-fw-rule
SQLSERVER_DATABASE_NAME=$(echo ${RESOURCE_GROUP_NAME}-db | tr -d "-")
